environment:
  - name: AWS_PROFILE
    action: unset
  - name: KUBECONFIG
    action: unset
  - name: GPG_TTY
    action: command
    value: tty
  - name: IPYTHONDIR
    value: "$HOME/.config/ipython"
  - name: LOCAL_INSTALL_DIR
    value: "$HOME/.local/opt"
    export: false
  - name: DOTNET_ROOT
    value: "$LOCAL_INSTALL_DIR/dotnet"
  - name: DOTNET_INSTALL_DIR
    value: "$DOTNET_ROOT"
  - name: SCOOP
    value: "$LOCAL_INSTALL_DIR/scoop"
  - name: PATH
    action: prepend
    value:
      - "$HOME/.local/bin"
      - "$HOME/.dotnet/tools"
      - "$LOCAL_INSTALL_DIR/bin"
      - "$DOTNET_INSTALL_DIR"
      - "$SCOOP/shims"
