".config/bash/bashrc.d/dracula-theme.bash":
  type: file
  url: https://raw.githubusercontent.com/dracula/tty/master/dracula-tty.sh
  refreshPeriod: "672h"

{{- $extension := "" }}
{{- if eq .chezmoi.os "windows" }}
{{-   $extension := ".exe" }}
{{- end }}
".local/opt/bin/oh-my-posh{{ $extension }}":
  type: file
  url: "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v{{ .versions.oh_my_posh }}/posh-{{ .chezmoi.os }}-{{ .chezmoi.arch }}{{ $extension }}"
  executable: true

".asdf":
  type: git-repo
  url: "https://github.com/asdf-vm/asdf.git"
  clone:
    args:
      - "--branch"
      - "{{ .versions.asdf }}"

{{- if .devtools }}
".local/opt/bin/dotnet-install.sh":
  type: file
  url: "https://dot.net/v1/dotnet-install.sh"
  executable: true
  refreshPeriod: "168h"
{{- end }}
