software:
  versions:
    asdf: "v0.11.3"
    dotnet:
      - LTS
      - STS
    lunarvim: "release-1.3/neovim-0.9"
    neovim:
      - "latest"
    nodejs:
      default: "latest:18"
      windows:
    password_store: "1.7.4"
    rust: 
      default: "latest:stable"
      windows:

  packages:
    - name: git
      windows:
        profile: never
      default: false

    - name: lunarvim
      package_manager: script
      windows:
        dependencies:
      default:
        dependencies:
          - pip3

    - name: chezmoi
      completions:
        chezmoi: chezmoi completion SHELL
      package_manager: other

    - name: neovim

    - name: nodejs
      profile: devtools
      windows:
        package: nodejs-lts
        completions:
          node:
            bash: node --completion-bash
          npm:
            bash: '& "C:\Program Files\git\bin\bash.exe" -c "npm completion"'
      default:
        completions:
          node:
            bash: node --completion-bash
          npm:
            bash: npm completion

    - name: rust
      profile: devtools
      windows:
        package: rustup-gnu

    - name: awscli
      profile: devtools
      windows: 
        package: aws
      default:
        dependencies:
          - unzip
          - pip3

    - name: azure-cli
      profile: devtools
      default:
        dependencies:
          - pip3
        dependency_check: 'export VENV="$(mktemp -d /tmp/bootstrap-dotfiles-venv-XXX)/venv" && python3 -m venv $VENV && $VENV/bin/python -m ensurepip'
        completions:
          az:
            bash: $(dirname $(asdf which az))/venv/bin/register-python-argcomplete az
      windows:
        completions:
          az:
            bash: |-
              & $env:SCOOP/apps/azure-cli/current/python.exe $env:SCOOP/apps/azure-cli/current/scripts/register-python-argcomplete az

    - name: github-cli
      profile: devtools
      completions:
        gh: gh completion --shell SHELL
      windows:
        package: gh

    - name: helm
      profile: devtools
      completions:
        helm: helm completion SHELL

    - name: k9s
      profile: devtools
      linux:
        repo: "https://github.com/looztra/asdf-k9s"

    - name: kubectl
      profile: devtools
      completions:
        kubectl: kubectl completion SHELL

    - name: terraform
      profile: devtools
      dependencies:
        - unzip

    - name: gcc
      windows:
      default: false

    - name: python
      windows:
      default: false

    - name: psfzf
      repo: extras
      windows:
      default: false

    - name: posh-git
      repo: extras
      default: false
      windows:

    - name: neovim-npm
      profile: devtools
      package: neovim
      package_manager: npm

    - name: tree-sitter-cli
      profile: devtools
      package_manager: npm

    - name: pynvim
      profile: devtools
      package_manager: pip

    - name: fd-find
      profile: devtools
      package_manager: cargo

    - name: ripgrep
      profile: devtools
      package_manager: cargo

    - name: nu
      profile: nushell
      package_manager: cargo

zsh:
  externalPlugins:
    - name: zsh-autosuggestions
      url: "https://github.com/zsh-users/zsh-autosuggestions"
    - name: zsh-syntax-highlighting
      url: "https://github.com/zsh-users/zsh-syntax-highlighting"
    - name: zsh-history-substring-search
      url: "https://github.com/zsh-users/zsh-history-substring-search"

