tools:
  asdf:
    versions: "v0.11.3"
    package_manager: external
  oh_my_posh:
    versions: "14.26.0"
    package_manager: external
  dotnet:
    versions: LTS
    package_manager: script
  lunarvim:
    versions: "release-1.2/neovim-0.8"
    package_manager: script
  lunarvim_installer:
    versions: "fc6873809934917b470bff1b072171879899a36b"
    package_manager: script
  chezmoi:
  neovim:
    versions: "0.8.3"
  nodejs:
    versions: "latest:lts"
  rust:
    versions: "latest:stable"
  awscli:
    group: devtools
  azure-cli:
    group: devtools
  github-cli:
    group: devtools
  helm:
    group: devtools
  k9s:
    group: devtools
    repo: "https://github.com/looztra/asdf-k9s"
  kubectl:
    group: devtools
