chezmoi:template:missing-key=zero
{{ joinPath .paths.relative.configHome "shrc.d" "dracula-theme.sh" | quote }}:
  type: file
  url: https://raw.githubusercontent.com/dracula/tty/master/dracula-tty.sh
  refreshPeriod: "672h"

{{ joinPath .paths.relative.configHome "alacritty" "dracula.yml" | quote }}:
  type: file
  url: https://raw.githubusercontent.com/dracula/alacritty/master/dracula.yml
  refreshPeriod: "672h"

{{- $posh_ext := eq .chezmoi.os "windows" | ternary ".exe" "" }}
{{- $posh_filename := (list "posh-" .chezmoi.os "-" .chezmoi.arch $posh_ext) | join "" }}
{{- $posh_version := .software.versions.oh_my_posh | default "latest" }}
{{- $posh_url_base := "https://github.com/JanDeDobbeleer/oh-my-posh/releases" }}
{{- $posh_url_path := eq $posh_version "latest"
                      | ternary
                        "latest/download"
                        ((list "download/v" $posh_version) | join "")
}}
{{ list (joinPath .paths.relative.localInstallBin "oh-my-posh") $posh_ext | join "" | quote }}:
  type: file
  url: "{{ $posh_url_base }}/{{ $posh_url_path }}/{{ $posh_filename }}"
  executable: true
  refreshPeriod: "168h"

{{- if and .profile.installSoftware ("asdf" | hasKey .paths.relative) }}
{{ .paths.relative.asdf | quote }}:
  type: git-repo
  url: "https://github.com/asdf-vm/asdf.git"
  clone:
    args:
      - "--branch"
      - "{{ .software.versions.asdf }}"
{{- end }}

{{- $dotnetInstall := "dotnet-install.sh" }}
{{- if eq .chezmoi.os "windows" }}
{{- $dotnetInstall = "dotnet-install.ps1" }}
{{- end }}
{{- if and .profile.devtools }}
{{ joinPath .paths.relative.localInstallSbin $dotnetInstall | quote }}:
  type: file
  url: {{ list "https://dot.net/v1" $dotnetInstall | join "/" | quote }}
  executable: true
  refreshPeriod: "168h"
{{- end }}

{{- if and .profile.installSoftware (ne "windows" .chezmoi.os) }}
{{ .paths.relative.passwordStore | quote }}:
  type: archive
  url: https://git.zx2c4.com/password-store/snapshot/password-store-{{ .software.versions.password_store }}.tar.xz
  stripComponents: 1
{{- end }}

{{- if .profile.installSoftware }}
{{ .paths.relative.lunarvimBase | quote }}:
  type: git-repo
  url: "https://github.com/LunarVim/LunarVim"
  refreshPeriod: "168h"
  clone:
    args:
      - "--branch"
      - "{{ .software.versions.lunarvim }}"
{{- end }}

{{- if .profile.nushell }}
{{ joinPath .paths.relative.configHome "nushell" "nu_scripts" | quote }}:
  type: git-repo
  url: "https://github.com/nushell/nu_scripts"
  refreshPeriod: "168h"
{{- end }}

{{- if ne "windows" .chezmoi.os }}
{{ joinPath .paths.relative.localInstall "oh-my-zsh" | quote }}:
  url: "https://github.com/ohmyzsh/ohmyzsh"
  type: git-repo
  refreshPeriod: "168h"
{{-   range .zsh.externalPlugins }}
{{ joinPath $.paths.relative.zshPlugins .name | quote }}:
  type: git-repo
  url: {{ .url | quote }}
  refreshPeriod: "168h"
{{-   end }}
{{- end }}

{{ .paths.relative.fzf | quote }}:
  type: archive
  url: {{ (gitHubLatestRelease "junegunn/fzf").TarballURL }}
  stripComponents: 1

{{ $gcmAssetPattern := dict
     "windows" "gcm-win-x86.*\\d\\.zip"
     "darwin" (list "gcm-osx-" .chezmoi.arch ".*\\d\\.tar.gz" | join "")
     "linux" (list "gcm-linux_" .chezmoi.arch ".*\\d\\.tar.gz" | join "")
-}}
{{ .paths.relative.gitCredentialManager | quote }}:
  type: archive
  exact: true
{{- if eq .chezmoi.os "darwin" }}
  stripComponents: 1
{{- end }}
  url: {{ template "gitHubReleaseAsset" (dict
    "repo" "git-ecosystem/git-credential-manager"
    "pattern" (.chezmoi.os | index $gcmAssetPattern)
  )
}}

{{ joinPath .paths.relative.configHome "xfce4" "colorschemes" "Dracula.theme" | quote }}:
  type: file
  url: {{ template "gitHubReleaseAsset" (dict
    "repo" "dracula/xfce4-terminal"
    "pattern" "Dracula.theme"
    )
  }}

{{ joinPath .paths.relative.dataHome "fonts" | quote }}:
  type: archive
  url: {{ template "gitHubReleaseAsset" (dict "repo" "ryanoasis/nerd-fonts" "pattern" "Hack.zip") }}
  exact: true
  include:
    - "*Mono*"
