tools:
  asdf:
    version: "v0.11.3"
    package_manager: external
  oh_my_posh:
    version: "14.26.0"
    package_manager: external
  dotnet:
    version: 
      - LTS
      - STS
    package_manager: script
  lunarvim:
    version: "release-1.2/neovim-0.8"
    package_manager: script
    dependencies:
      - pip3
  lunarvim_installer:
    version: "fc6873809934917b470bff1b072171879899a36b"
    package_manager: script
  chezmoi:
    completion:
      command: chezmoi completion SHELL
  neovim:
    version: 
      - "latest:0.8"
      - "latest:0.9"
  nodejs:
    version: "latest:lts"
    completion:
      - binary: node
        command: node --completion-bash
      - binary: npm
        command: npm completion
  rust:
    version: "latest:stable"
  awscli:
    group: devtools
    dependencies:
      - unzip
      - pip3
    completion:
      binary: aws
      command: complete -C aws_completer aws
      eval: false
  azure-cli:
    group: devtools
    dependencies:
      - pip3
    dependency_check: 'export VENV="$(mktemp -d /tmp/bootstrap-dotfiles-venv-XXX)/venv" && python3 -m venv $VENV && $VENV/bin/python -m ensurepip'
    completion:
      binary: az
      command: $(dirname $(asdf which az))/venv/bin/register-python-argcomplete az
  github-cli:
    group: devtools
    completion:
      binary: gh
      command: gh completion --shell SHELL
  helm:
    group: devtools
    completion:
      command: helm completion SHELL
  k9s:
    group: devtools
    repo: "https://github.com/looztra/asdf-k9s"
  kubectl:
    group: devtools
    completion:
      command: kubectl completion SHELL

environment:
  - name: AWS_PROFILE
    action: unset
  - name: KUBECONFIG
    action: unset
  - name: GPG_TTY
    action: command
    value: tty
  - name: IPYTHONDIR
    value: "$HOME/.config/ipython"
  - name: LOCAL_INSTALL_DIR
    value: "$HOME/.local/opt"
    export: false
  - name: DOTNET_ROOT
    value: "$LOCAL_INSTALL_DIR/dotnet"
  - name: DOTNET_INSTALL_DIR
    value: "$DOTNET_ROOT"
  - name: PATH 
    action: prepend
    value:
      - "$HOME/.local/bin"
      - "$HOME/.dotnet/tools"
      - "$DOTNET_INSTALL_DIR"
      - "$LOCAL_INSTALL_DIR/bin"
