chezmoi:template:missing-key=zero
{{ joinPath .paths.relative.configHome "shrc.d" "dracula-theme.sh" | quote }}:
  type: file
  url: https://raw.githubusercontent.com/dracula/tty/master/dracula-tty.sh
  refreshPeriod: "672h"

{{ joinPath .paths.relative.configHome "alacritty" "dracula.yml" | quote }}:
  type: file
  url: https://raw.githubusercontent.com/dracula/alacritty/master/dracula.yml
  refreshPeriod: "672h"

{{- $posh_ext := eq .chezmoi.os "windows" | ternary ".exe" "" }}
{{- $posh_filename := (list "posh-" .chezmoi.os "-" .chezmoi.arch $posh_ext) | join "" }}
{{- $posh_version := .software.versions.oh_my_posh | default "latest" }}
{{- $posh_url_base := "https://github.com/JanDeDobbeleer/oh-my-posh/releases" }}
{{- $posh_url_path := eq $posh_version "latest"
                      | ternary
                        "latest/download"
                        ((list "download/v" $posh_version) | join "")
}}
{{ list (joinPath .paths.relative.localInstallBin "oh-my-posh") $posh_ext | join "" | quote }}:
  type: file
  url: "{{ $posh_url_base }}/{{ $posh_url_path }}/{{ $posh_filename }}"
  executable: true
  refreshPeriod: "168h"

{{- if "asdf" | hasKey .paths.relative }}
{{ .paths.relative.asdf | quote }}:
  type: git-repo
  url: "https://github.com/asdf-vm/asdf.git"
  clone:
    args:
      - "--branch"
      - "{{ .software.versions.asdf }}"
{{- end }}

{{- if .profile.nushell }}
{{ joinPath .paths.relative.configHome "nushell" "nu_scripts" | quote }}:
  type: git-repo
  url: "https://github.com/nushell/nu_scripts"
  refreshPeriod: "168h"
{{- end }}

{{- if ne "windows" .chezmoi.os }}
{{ joinPath .paths.relative.localInstall "oh-my-zsh" | quote }}:
  url: "https://github.com/ohmyzsh/ohmyzsh"
  type: git-repo
  refreshPeriod: "168h"
{{-   range .zsh.externalPlugins }}
{{ joinPath $.paths.relative.zshPlugins .name | quote }}:
  type: git-repo
  url: {{ .url | quote }}
  refreshPeriod: "168h"
{{-   end }}
{{- end }}

{{ .paths.relative.fzf | quote }}:
  type: archive
  url: {{ (gitHubLatestRelease "junegunn/fzf").TarballURL }}
  stripComponents: 1

{{ joinPath .paths.relative.configHome "xfce4" "colorschemes" "Dracula.theme" | quote }}:
  type: file
  url: {{ template "gitHubReleaseAsset" (dict
    "repo" "dracula/xfce4-terminal"
    "pattern" "Dracula.theme"
    )
  }}

{{ joinPath .paths.relative.dataHome "fonts" | quote }}:
  type: archive
  url: {{ template "gitHubReleaseAsset" (dict "repo" "ryanoasis/nerd-fonts" "pattern" "Hack.zip") }}
  exact: true
  include:
    - "*Mono*"
