tools:
  asdf:
    version: "v0.11.3"
    package_manager: external
  oh_my_posh:
    version: "14.26.0"
    package_manager: external
  dotnet:
    version: 
      - LTS
      - STS
    package_manager: script
  lunarvim:
    version: "release-1.2/neovim-0.8"
    package_manager: script
    dependencies:
      - pip3
  lunarvim_installer:
    version: "fc6873809934917b470bff1b072171879899a36b"
    package_manager: script
  chezmoi:
  neovim:
    version: 
      - "latest:0.8"
      - "latest:0.9"
  nodejs:
    version: "latest:lts"
  rust:
    version: "latest:stable"
  awscli:
    group: devtools
    dependencies:
      - unzip
      - pip3
  azure-cli:
    group: devtools
    dependencies:
      - pip3
    dependency_check: 'export VENV="$(mktemp -d /tmp/bootstrap-dotfiles-venv-XXX)/venv" && python3 -m venv $VENV && $VENV/bin/python -m ensurepip'
  github-cli:
    group: devtools
  helm:
    group: devtools
  k9s:
    group: devtools
    repo: "https://github.com/looztra/asdf-k9s"
  kubectl:
    group: devtools
