chezmoi:template:missing-key=zero
".config/bash/bashrc.d/dracula-theme.bash":
  type: file
  url: https://raw.githubusercontent.com/dracula/tty/master/dracula-tty.sh
  refreshPeriod: "672h"

{{- $posh_ext := eq .chezmoi.os "windows" | ternary ".exe" "" }}
{{- $posh_filename := (list "posh-" .chezmoi.os "-" .chezmoi.arch $posh_ext) | join "" }}
{{- $posh_version := .software.versions.oh_my_posh | default "latest" }}
{{- $posh_url_base := "https://github.com/JanDeDobbeleer/oh-my-posh/releases" }}
{{- $posh_url_path := eq $posh_version "latest"
                      | ternary
                        "latest/download"
                        ((list "download/v" $posh_version) | join "")
}}
".local/opt/bin/oh-my-posh{{ $posh_ext }}":
  type: file
  url: "{{ $posh_url_base }}/{{ $posh_url_path }}/{{ $posh_filename }}"
  executable: true
  refreshPeriod: "168h"

{{- if ne .chezmoi.os "windows" }}
".asdf":
  type: git-repo
  url: "https://github.com/asdf-vm/asdf.git"
  clone:
    args:
      - "--branch"
      - "{{ .software.versions.asdf }}"
{{- end }}

{{- if .devtools }}
"{{ joinPath .paths.localInstallSbin "dotnet-install.ps1"}}":
  type: file
  url: "https://dot.net/v1/dotnet-install.ps1"
  executable: true
  refreshPeriod: "168h"
{{- end }}

".local/share/lunarvim/lvim":
  type: git-repo
  url: "https://github.com/LunarVim/LunarVim"
  refreshPeriod: "168h"
  clone:
    args:
      - "--branch"
      - "{{ .software.versions.lunarvim }}"

".config/nushell/nu_scripts":
  type: git-repo
  url: "https://github.com/nushell/nu_scripts"
  refreshPeriod: "168h"
