chezmoi:template:missing-key=zero
{{ joinPath .paths.relative.configHome "shrc.d" "dracula-theme.sh" | quote }}:
  type: file
  url: https://raw.githubusercontent.com/dracula/tty/master/dracula-tty.sh
  refreshPeriod: "672h"

{{- $posh_ext := eq .chezmoi.os "windows" | ternary ".exe" "" }}
{{- $posh_filename := (list "posh-" .chezmoi.os "-" .chezmoi.arch $posh_ext) | join "" }}
{{- $posh_version := .software.versions.oh_my_posh | default "latest" }}
{{- $posh_url_base := "https://github.com/JanDeDobbeleer/oh-my-posh/releases" }}
{{- $posh_url_path := eq $posh_version "latest"
                      | ternary
                        "latest/download"
                        ((list "download/v" $posh_version) | join "")
}}
{{ list (joinPath .paths.relative.localInstallBin "oh-my-posh") $posh_ext | join "" | quote }}:
  type: file
  url: "{{ $posh_url_base }}/{{ $posh_url_path }}/{{ $posh_filename }}"
  executable: true
  refreshPeriod: "168h"

{{- if ne .chezmoi.os "windows" }}
{{ .paths.relative.asdf | quote }}:
  type: git-repo
  url: "https://github.com/asdf-vm/asdf.git"
  clone:
    args:
      - "--branch"
      - "{{ .software.versions.asdf }}"
{{- end }}

{{- if and .devtools (ne .chezmoi.os "windows") }}
{{ joinPath .paths.relative.localInstallSbin "dotnet-install.sh" |quote }}:
  type: file
  url: "https://dot.net/v1/dotnet-install.sh"
  executable: true
  refreshPeriod: "168h"
{{- end }}

{{ .paths.relative.lunarvimBase | quote }}:
  type: git-repo
  url: "https://github.com/LunarVim/LunarVim"
  refreshPeriod: "168h"
  clone:
    args:
      - "--branch"
      - "{{ .software.versions.lunarvim }}"

{{ joinPath .paths.relative.configHome "nushell" "nu_scripts" | quote }}:
  type: git-repo
  url: "https://github.com/nushell/nu_scripts"
  refreshPeriod: "168h"

{{ joinPath .paths.relative.localInstall "oh-my-zsh" | quote }}:
  url: "https://github.com/ohmyzsh/ohmyzsh"
  type: git-repo
  refreshPeriod: "168h"
{{-   range .zsh.externalPlugins }}
{{ joinPath $.paths.relative.zshPlugins .name | quote }}:
  type: git-repo
  url: {{ .url | quote }}
  refreshPeriod: "168h"
{{-   end }}

{{ joinPath .paths.relative.fzf | quote }}:
  type: git-repo
  url: https://github.com/junegunn/fzf
  refreshPeriod: "168h"
