".config/bash/bashrc.d/dracula-theme.bash":
  type: file
  url: https://raw.githubusercontent.com/dracula/tty/master/dracula-tty.sh
  refreshPeriod: "672h"

{{- $extension := "" }}
{{- if eq .chezmoi.os "windows" }}
{{-   $extension := ".exe" }}
{{- end }}
".local/opt/bin/oh-my-posh{{ $extension }}":
  type: file
  url: "https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v{{ .versions.oh_my_posh }}/posh-{{ .chezmoi.os }}-{{ .chezmoi.arch }}{{ $extension }}"
