versions:
  asdf: "v0.11.3"
  oh_my_posh: "14.26.0"
  dotnet:
    - LTS
  lunarvim: "release-1.2/neovim-0.8"
  lunarvim_installer: "fc6873809934917b470bff1b072171879899a36b"

asdf:
  chezmoi:
  neovim:
    versions: "0.8.3"
  nodejs:
    versions: "latest:lts"
  rust:
    versions: "latest:stable"
  awscli:
    group: devtools
  azure-cli:
    group: devtools
  github-cli:
    group: devtools
  helm:
    group: devtools
  k9s:
    group: devtools
    repo: "https://github.com/looztra/asdf-k9s"
  kubectl:
    group: devtools
