[tools]
azure-cli = "latest"
neovim = "latest"
k9s = "latest"
github-cli = "latest"
helm = "latest"
lazygit = "latest"
poetry = "latest"
terraform = "1.5.7"
awscli = "latest"
step = "latest"
eksctl = "latest"
terragrunt = "latest"
kubectl = "latest"
lazydocker = "latest"

[settings]
legacy_version_file = false
