#!/bin/bash

# Created by argbash-init v2.10.0
# ARG_HELP([Installs and configures the dotfiles])
# ARG_OPTIONAL_SINGLE([branch],[b],[Branch to install],[origin/main])
# ARG_OPTIONAL_SINGLE([destination],[d],[Install location on filesystem],[~/.config/dotfiles])
# ARG_LEFTOVERS([Parameters to pass to configure])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='hbd'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_leftovers=()
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_branch="origin/main"
_arg_destination="~/.config/dotfiles"


print_help()
{
	printf '%s\n' "Installs and configures the dotfiles"
	printf 'Usage: %s [-h|--help] [-b|--branch <arg>] [-d|--destination <arg>] ... \n' "$0"
	printf '\t%s\n' "... : Parameters to pass to configure"
	printf '\t%s\n' "-h, --help: Prints help"
	printf '\t%s\n' "-b, --branch: Branch to install (default: 'origin/main')"
	printf '\t%s\n' "-d, --destination: Install location on filesystem (default: '~/.config/dotfiles')"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			-b|--branch)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_branch="$2"
				shift
				;;
			--branch=*)
				_arg_branch="${_key##--branch=}"
				;;
			-b*)
				_arg_branch="${_key##-b}"
				;;
			-d|--destination)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_destination="$2"
				shift
				;;
			--destination=*)
				_arg_destination="${_key##--destination=}"
				;;
			-d*)
				_arg_destination="${_key##-d}"
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names=""
	_our_args=$((${#_positionals[@]} - 0))
	for ((ii = 0; ii < _our_args; ii++))
	do
		_positional_names="$_positional_names _arg_leftovers[$((ii + 0))]"
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


destination=$_arg_destination
branch=$_arg_branch
configure_options=$_arg_leftovers

function worktree_exists {
    git worktree list | awk '{ print $1 }' | grep -q $destination
}

if worktree_exists ; then
    echo "Already installed ($destination already exists)"
    echo "Checking out branch $branch..."
    (cd $destination && git checkout --detach $branch)
else
    echo "Creating installation $destination using branch $branch..."
    git worktree add --detach $destination $branch
fi

echo
echo "Configuring..."
$destination/configure-all.sh $configure_options

echo
echo "Complete."

# ] <-- needed because of Argbash
