version: '3'

vars:
  TEST_ROOT: '{{.TASKFILE_DIR}}'
  TESTS_DIR: '{{.TASKFILE_DIR}}/tests'

silent: false

tasks:
  test:incus:debian:
    desc: Run install-tools test in Debian Incus VM
    cmds:
      - task: _test:incus
        vars:
          IMAGE: images:debian/13/cloud
          DISTRO: debian
          INSTALL_TOOLS_ARGS: --no-nix-daemon --no-sudo-password-prompt

  test:incus:ubuntu:
    desc: Run install-tools test in Ubuntu Incus VM
    cmds:
      - task: _test:incus
        vars:
          IMAGE: images:ubuntu/24.04/cloud
          DISTRO: ubuntu
          INSTALL_TOOLS_ARGS: --no-nix-daemon --no-sudo-password-prompt

  test:incus:fedora:
    desc: Run install-tools test in Fedora Incus VM
    cmds:
      - task: _test:incus
        vars:
          IMAGE: images:fedora/43/cloud
          DISTRO: fedora
          INSTALL_TOOLS_ARGS: --no-nix-daemon --no-sudo-password-prompt

  test:incus:arch:
    desc: Run install-tools test in Arch Incus VM
    cmds:
      - task: _test:incus
        vars:
          IMAGE: images:archlinux/current/cloud
          DISTRO: arch
          INSTALL_TOOLS_ARGS: --no-nix-daemon --no-sudo-password-prompt

  test:incus:tumbleweed:
    desc: Run install-tools test in openSUSE Tumbleweed Incus VM
    cmds:
      - task: _test:incus
        vars:
          IMAGE: images:opensuse/tumbleweed/cloud
          DISTRO: tumbleweed
          INSTALL_TOOLS_ARGS: --no-nix-daemon --no-sudo-password-prompt

  test:incus:reset:debian:
    desc: Delete cached Debian Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:debian/13/cloud
          DISTRO: debian

  test:incus:reset:ubuntu:
    desc: Delete cached Ubuntu Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:ubuntu/24.04/cloud
          DISTRO: ubuntu

  test:incus:reset:fedora:
    desc: Delete cached Fedora Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:fedora/43/cloud
          DISTRO: fedora

  test:incus:reset:arch:
    desc: Delete cached Arch Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:archlinux/current/cloud
          DISTRO: arch

  test:incus:reset:tumbleweed:
    desc: Delete cached openSUSE Tumbleweed Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:opensuse/tumbleweed/cloud
          DISTRO: tumbleweed

  test:incus:reset:all:
    desc: Delete all cached Incus VMs used by install-tools tests
    cmds:
      - task: test:incus:reset:debian
      - task: test:incus:reset:ubuntu
      - task: test:incus:reset:fedora
      - task: test:incus:reset:arch
      - task: test:incus:reset:tumbleweed

  test:mac:
    desc: Run macOS install-tools test
    cmds:
      - "{{.TESTS_DIR}}/test-install-tools.sh"

  test:win:
    desc: Run Windows install-tools test
    cmds:
      - pwsh -NoLogo -NoProfile -File "{{.TESTS_DIR}}/test-install-tools.ps1"

  _test:incus:
    internal: true
    requires:
      vars: [IMAGE, DISTRO]
    cmds:
      - DISTRO="{{.DISTRO}}" IMAGE="{{.IMAGE}}" INSTALL_TOOLS_ARGS="{{.INSTALL_TOOLS_ARGS}}" TEST_ROOT="{{.TEST_ROOT}}" "{{.TESTS_DIR}}/incus-install-tools-test.sh"

  _test:incus:reset:
    internal: true
    requires:
      vars: [IMAGE, DISTRO]
    cmds:
      - DISTRO="{{.DISTRO}}" IMAGE="{{.IMAGE}}" "{{.TESTS_DIR}}/incus-reset-test-vm.sh"
