version: '3'

vars:
  TEST_ROOT: '{{.TASKFILE_DIR}}'
  TESTS_DIR: '{{.TASKFILE_DIR}}/tests'

silent: false

tasks:
  test:incus:debian:
    desc: Run install-tools test in Debian Incus VM
    cmds:
      - DISTRO="debian" DISTRO_VERSION="13" IMAGE="images:debian/13/cloud" INSTALL_TOOLS_ARGS="--nix-daemon --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/incus-install-tools-test.sh"

  test:incus:ubuntu:
    desc: Run install-tools test in Ubuntu Incus VM
    cmds:
      - DISTRO="ubuntu" DISTRO_VERSION="2404" IMAGE="images:ubuntu/24.04/cloud" INSTALL_TOOLS_ARGS="--nix-daemon --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/incus-install-tools-test.sh"

  test:incus:fedora:
    desc: Run install-tools test in Fedora Incus VM
    cmds:
      - DISTRO="fedora" DISTRO_VERSION="43" IMAGE="images:fedora/43/cloud" INSTALL_TOOLS_ARGS="--nix-daemon --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/incus-install-tools-test.sh"

  test:incus:arch:
    desc: Run install-tools test in Arch Incus VM
    cmds:
      - DISTRO="arch" DISTRO_VERSION="" IMAGE="images:archlinux/current/cloud" INSTALL_TOOLS_ARGS="--nix-daemon --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/incus-install-tools-test.sh"

  test:incus:tumbleweed:
    desc: Run install-tools test in openSUSE Tumbleweed Incus VM
    cmds:
      - DISTRO="tumbleweed" DISTRO_VERSION="" IMAGE="images:opensuse/tumbleweed/cloud" INSTALL_TOOLS_ARGS="--nix-daemon --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/incus-install-tools-test.sh"

  test:incus:all:
    desc: Run all Incus install-tools tests sequentially
    cmds:
      - task test:incus:debian
      - task test:incus:ubuntu
      - task test:incus:fedora
      - task test:incus:arch
      - task test:incus:tumbleweed

  test:incus:reset:debian:
    desc: Delete cached Debian Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:debian/13/cloud
          DISTRO: debian
          DISTRO_VERSION: "13"

  test:incus:reset:ubuntu:
    desc: Delete cached Ubuntu Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:ubuntu/24.04/cloud
          DISTRO: ubuntu
          DISTRO_VERSION: "24_04"

  test:incus:reset:fedora:
    desc: Delete cached Fedora Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:fedora/43/cloud
          DISTRO: fedora
          DISTRO_VERSION: "43"

  test:incus:reset:arch:
    desc: Delete cached Arch Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:archlinux/current/cloud
          DISTRO: arch
          DISTRO_VERSION: ""

  test:incus:reset:tumbleweed:
    desc: Delete cached openSUSE Tumbleweed Incus VM used by install-tools tests
    cmds:
      - task: _test:incus:reset
        vars:
          IMAGE: images:opensuse/tumbleweed/cloud
          DISTRO: tumbleweed
          DISTRO_VERSION: ""

  test:incus:reset:all:
    desc: Delete all cached Incus VMs used by install-tools tests
    cmds:
      - task: test:incus:reset:debian
      - task: test:incus:reset:ubuntu
      - task: test:incus:reset:fedora
      - task: test:incus:reset:arch
      - task: test:incus:reset:tumbleweed

  test:docker:debian:
    desc: Run install-tools test in Debian Docker container
    cmds:
      - DISTRO="debian" DISTRO_VERSION="13" IMAGE="debian:13" INSTALL_TOOLS_ARGS="--nix-daemon-direct --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/docker-install-tools-test.sh"

  test:docker:ubuntu:
    desc: Run install-tools test in Ubuntu Docker container
    cmds:
      - DISTRO="ubuntu" DISTRO_VERSION="2404" IMAGE="ubuntu:24.04" INSTALL_TOOLS_ARGS="--nix-daemon-direct --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/docker-install-tools-test.sh"

  test:docker:fedora:
    desc: Run install-tools test in Fedora Docker container
    cmds:
      - DISTRO="fedora" DISTRO_VERSION="43" IMAGE="fedora:43" INSTALL_TOOLS_ARGS="--nix-daemon-direct --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/docker-install-tools-test.sh"

  test:docker:arch:
    desc: Run install-tools test in Arch Docker container
    cmds:
      - DISTRO="arch" DISTRO_VERSION="" IMAGE="archlinux:latest" INSTALL_TOOLS_ARGS="--nix-daemon-direct --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/docker-install-tools-test.sh"

  test:docker:tumbleweed:
    desc: Run install-tools test in openSUSE Tumbleweed Docker container
    cmds:
      - DISTRO="tumbleweed" DISTRO_VERSION="" IMAGE="opensuse/tumbleweed:latest" INSTALL_TOOLS_ARGS="--nix-daemon-direct --no-sudo-password-prompt" TEST_ROOT="{{.TEST_ROOT}}" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/docker-install-tools-test.sh"

  test:docker:all:
    desc: Run all Docker install-tools tests sequentially
    cmds:
      - task test:docker:debian
      - task test:docker:ubuntu
      - task test:docker:fedora
      - task test:docker:arch
      - task test:docker:tumbleweed

  test:mac:
    desc: Run macOS install-tools test
    cmds:
      - DOTFILES="{{.TEST_ROOT}}/dotfiles" TEST_VERBOSE="{{if .CLI_VERBOSE}}1{{else}}0{{end}}" "{{.TESTS_DIR}}/test-install-tools.sh"

  test:win:
    desc: Run Windows install-tools test
    cmds:
      - CI="true" DOTFILES="{{.TEST_ROOT}}/dotfiles" pwsh -NoLogo -NoProfile -File "{{.TESTS_DIR}}/test-install-tools.ps1" {{if .CLI_VERBOSE}}-VerboseLogs{{end}}

  _test:incus:reset:
    internal: true
    requires:
      vars: [IMAGE, DISTRO]
    cmds:
      - DISTRO="{{.DISTRO}}" DISTRO_VERSION="{{.DISTRO_VERSION}}" IMAGE="{{.IMAGE}}" "{{.TESTS_DIR}}/incus-reset-test-vm.sh"
