version: 3
profiles: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Nord
    foreground: '#d8dee9'
    background: '#2e3440'
    cursor: '#d8dee9'
    colors:
      - '#3b4252'
      - '#bf616a'
      - '#a3be8c'
      - '#ebcb8b'
      - '#81a1c1'
      - '#b48ead'
      - '#88c0d0'
      - '#e5e9f0'
      - '#373e4d'
      - '#94545d'
      - '#809575'
      - '#b29e75'
      - '#68809a'
      - '#8c738c'
      - '#6d96a5'
      - '#aeb3bb'
  font: Hack Nerd Font Mono
  copyAsHTML: false
  autoOpen: true
  customColorSchemes: []
  cursor: beam
appearance:
  vibrancy: false
  css: |-
    terminaltab ::-webkit-scrollbar {
      display: none;
    }
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - serial
  - telnet
profileDefaults:
  ssh:
    disableDynamicTitle: true
recoverTabs: false
