return {
  debugging = {
    breakpoint = "",
    conditional_breakpoint = "",
    logpoint = "",
    stopped = "",
  },
  diagnostic = {
    error = "",
    warn = "",
    info = "", -- suggestion :nf-cod-inf
    hint = "", -- silent
  },
  file = {
    unnamed = "󰡯", -- nf-md-file_question
    newfile = "", -- nf-md-file_question
    modified = "●",
    readonly = "󰌾", -- nf-md-lock
    folder_closed = "",
    folder_open = "",
    folder_empty = "󰉖",
    folder_empty_open = "󰷏",
  },
  kinds = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  history = "",
  command = ">",
}
