[general]
live_config_reload = true

import = ["~/.config/alacritty/config.toml"]

[window.padding]
x = 8
y = 8

[[keyboard.bindings]]
action = "ReceiveChar"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "Return"
mods = "Alt"
