return {
  "folke/todo-comments.nvim",
  opts = {
    highlight = {
      comments_only = false,
      pattern = [[<(KEYWORDS)>]],
      keyword = "bg",
      after = "",
    },
    keywords = {
      nord0 = { color = "#2e3440" },
      nord1 = { color = "#3b4252" },
      nord2 = { color = "#434c5e" },
      nord3 = { color = "#4c566a" },
      nord4 = { color = "#d8dee9" },
      nord5 = { color = "#e5e9f0" },
      nord6 = { color = "#eceff4" },
      nord7 = { color = "#8fbcbb" },
      nord8 = { color = "#88c0d0" },
      nord9 = { color = "#81a1c1" },
      nord10 = { color = "#5e81ac" },
      nord11 = { color = "#bf616a" },
      nord12 = { color = "#d08770" },
      nord13 = { color = "#ebcb8b" },
      nord14 = { color = "#a3be8c" },
      nord15 = { color = "#b48ead" },

      -- catppuccin mocha
      cpm_rosewater = { color = "#f5e0dc" },
      cpm_flamingo = { color = "#f2cdcd" },
      cpm_pink = { color = "#f5c2e7" },
      cpm_mauve = { color = "#cba6f7" },
      cpm_red = { color = "#f38ba8" },
      cpm_maroon = { color = "#eba0ac" },
      cpm_peach = { color = "#fab387" },
      cpm_yellow = { color = "#f9e2af" },
      cpm_green = { color = "#a6e3a1" },
      cpm_teal = { color = "#94e2d5" },
      cpm_sky = { color = "#89dceb" },
      cpm_sapphire = { color = "#74c7ec" },
      cpm_blue = { color = "#89b4fa" },
      cpm_lavender = { color = "#b4befe" },
      cpm_text = { color = "#cdd6f4" },
      cpm_subtext1 = { color = "#bac2de" },
      cpm_subtext0 = { color = "#a6adc8" },
      cpm_overlay2 = { color = "#9399b2" },
      cpm_overlay1 = { color = "#7f849c" },
      cpm_overlay0 = { color = "#6c7086" },
      cpm_surface2 = { color = "#585b70" },
      cpm_surface1 = { color = "#45475a" },
      cpm_surface0 = { color = "#313244" },
      cpm_base = { color = "#1e1e2e" },
      cpm_mantle = { color = "#181825" },
      cpm_crust = { color = "#11111b" },
    },
    search = {
      pattern = [[\b(KEYWORDS)\b]],
    },
  },
}
