highlight link LspErrorHighlight ErrorMsg
highlight link LspErrorText Error
highlight link LspWarningHighlight WarningMsg
highlight link LspWarningText Warning
highlight link lspReference DraculaInfoLine
