function catppuccin_mocha_colors {
	cpm_rosewater="#f5e0dc"
	cpm_flamingo="#f2cdcd"
	cpm_pink="#f5c2e7"
	cpm_mauve="#cba6f7"
	cpm_red="#f38ba8"
	cpm_maroon="#eba0ac"
	cpm_peach="#fab387"
	cpm_yellow="#f9e2af"
	cpm_green="#a6e3a1"
	cpm_teal="#94e2d5"
	cpm_sky="#89dceb"
	cpm_sapphire="#74c7ec"
	cpm_blue="#89b4fa"
	cpm_lavender="#b4befe"
	cpm_text="#cdd6f4"
	cpm_subtext1="#bac2de"
	cpm_subtext0="#a6adc8"
	cpm_overlay2="#9399b2"
	cpm_overlay1="#7f849c"
	cpm_overlay0="#6c7086"
	cpm_surface2="#585b70"
	cpm_surface1="#45475a"
	cpm_surface0="#313244"
	cp_base="#1e1e2e"
	cpm_mantle="#181825"
	cpm_crust="#11111b"

	segment_bg="$cpm_mantle"
	segment_accent_bright="$cpm_blue"
	segment_accent_dark="$cpm_surface0"
	prefix_accent_bright="$cpm_green"
	window_accent_bright="$cpm_sky"
	window_accent_dark="$cpm_surface0"
	suspend_accent_bright="$cpm_surface0"
	suspend_accent_dark="$cpm_mantle"

	tmux set -g @theme468-status-foreground "$segment_accent_bright"
	tmux set -g @theme468-status-background "$segment_bg"
	tmux set -g @theme468-mode-foreground "$cpm_text"
	tmux set -g @theme468-mode-background "$cpm_mantle"

	tmux set -g @theme468-window-foreground "$window_accent_bright"
	tmux set -g @theme468-window-background "$window_accent_dark"
	tmux set -g @theme468-window-foreground-suspended "$suspend_accent_bright"
	tmux set -g @theme468-window-background-suspended "$suspend_accent_dark"
	tmux set -g @theme468-window-current-foreground "$window_accent_dark"
	tmux set -g @theme468-window-current-background "$window_accent_bright"
	tmux set -g @theme468-window-current-foreground-suspended "$window_accent_bright"
	tmux set -g @theme468-window-current-background-suspended "$window_accent_dark"

	for i in session host; do
		tmux set -g @theme468-segment-$i-foreground "$segment_accent_dark"
		tmux set -g @theme468-segment-$i-background "$segment_accent_bright"
		tmux set -g @theme468-segment-$i-foreground-suspended "$suspend_accent_bright"
		tmux set -g @theme468-segment-$i-background-suspended "$suspend_accent_dark"
		tmux set -g @theme468-segment-$i-foreground-prefix "$segment_accent_dark"
		tmux set -g @theme468-segment-$i-background-prefix "$prefix_accent_bright"
	done

	tmux set -g @theme468-segment-date-foreground "$segment_accent_bright"
	tmux set -g @theme468-segment-date-background "$segment_accent_dark"
	tmux set -g @theme468-segment-date-foreground-suspended "$suspend_accent_bright"
	tmux set -g @theme468-segment-date-background-suspended "$suspend_accent_dark"

	tmux set -g @theme468-message-style-foreground "$cpm_blue"
	tmux set -g @theme468-message-style-background "$nord0"
	tmux set -g @theme468-message-command-style-foreground "$nord10"
	tmux set -g @theme468-message-command-style-background "$nord0"
	tmux set -g @theme468-copy-mode-match-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-match-style-background "$nord10"
	tmux set -g @theme468-copy-mode-current-match-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-current-match-style-background "$cpm_blue"
	tmux set -g @theme468-copy-mode-mark-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-mark-style-background "$cpm_blue"

	tmux set -g @theme468-display-panes-color "$window_accent_dark"
	tmux set -g @theme468-display-panes-active-color "$window_accent_bright"
	tmux set -g @theme468-pane-border-foreground "$window_accent_dark"
	tmux set -g @theme468-pane-border-foreground-suspended "$suspend_accent_dark"
	tmux set -g @theme468-pane-border-background "default"
	tmux set -g @theme468-pane-active-border-foreground "$window_accent_bright"
	tmux set -g @theme468-pane-active-border-foreground-suspended "$window_accent_dark"
	tmux set -g @theme468-pane-active-border-background "default"

	unset -f catppuccin_mocha_colors
} && catppuccin_mocha_colors
