function nord_colors {
	nord0="#2e3440"
	nord1="#3b4252"
	nord2="#434c5e"
	nord3="#4c566a"
	nord4="#d8dee9"
	nord5="#e5e9f0"
	nord6="#eceff4"
	nord7="#8fbcbb"
	nord8="#88c0d0"
	nord9="#81a1c1"
	nord10="#5e81ac"
	nord11="#bf616a"
	nord12="#d08770"
	nord13="#ebcb8b"
	nord14="#a3be8c"
	nord15="#b48ead"

	segment_bg="$nord1"
	segment_accent_bright="$nord8"
	segment_accent_dark="$nord3"
	prefix_accent_bright="$nord4"
	window_accent_bright="$nord10"
	window_accent_dark="$nord3"
	suspend_accent_bright="$nord3"
	suspend_accent_dark="$segment_bg"

	tmux set -g @theme468-status-foreground "$segment_accent_bright"
	tmux set -g @theme468-status-background "$segment_bg"
	tmux set -g @theme468-mode-foreground "$nord0"
	tmux set -g @theme468-mode-background "$nord10"

	tmux set -g @theme468-window-foreground "$window_accent_bright"
	tmux set -g @theme468-window-background "$window_accent_dark"
	tmux set -g @theme468-window-foreground-suspended "$suspend_accent_bright"
	tmux set -g @theme468-window-background-suspended "$suspend_accent_dark"
	tmux set -g @theme468-window-current-foreground "$window_accent_dark"
	tmux set -g @theme468-window-current-background "$window_accent_bright"
	tmux set -g @theme468-window-current-foreground-suspended "$window_accent_bright"
	tmux set -g @theme468-window-current-background-suspended "$window_accent_dark"

	for i in session host; do
		tmux set -g @theme468-segment-$i-foreground "$segment_accent_dark"
		tmux set -g @theme468-segment-$i-background "$segment_accent_bright"
		tmux set -g @theme468-segment-$i-foreground-suspended "$suspend_accent_bright"
		tmux set -g @theme468-segment-$i-background-suspended "$suspend_accent_dark"
		tmux set -g @theme468-segment-$i-foreground-prefix "$segment_accent_dark"
		tmux set -g @theme468-segment-$i-background-prefix "$prefix_accent_bright"
	done

	tmux set -g @theme468-segment-date-foreground "$segment_accent_bright"
	tmux set -g @theme468-segment-date-background "$segment_accent_dark"
	tmux set -g @theme468-segment-date-foreground-suspended "$suspend_accent_bright"
	tmux set -g @theme468-segment-date-background-suspended "$suspend_accent_dark"

	tmux set -g @theme468-segment-date-foreground "$nord8"
	tmux set -g @theme468-segment-date-background "$nord3"

	tmux set -g @theme468-message-style-foreground "$nord8"
	tmux set -g @theme468-message-style-background "$nord0"
	tmux set -g @theme468-message-command-style-foreground "$nord10"
	tmux set -g @theme468-message-command-style-background "$nord0"
	tmux set -g @theme468-copy-mode-match-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-match-style-background "$nord10"
	tmux set -g @theme468-copy-mode-current-match-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-current-match-style-background "$nord8"
	tmux set -g @theme468-copy-mode-mark-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-mark-style-background "$nord8"

	tmux set -g @theme468-display-panes-color "$window_accent_dark"
	tmux set -g @theme468-display-panes-active-color "$window_accent_bright"
	tmux set -g @theme468-pane-border-foreground "$window_accent_dark"
	tmux set -g @theme468-pane-border-foreground-suspended "$suspend_accent_dark"
	tmux set -g @theme468-pane-border-background "default"
	tmux set -g @theme468-pane-active-border-foreground "$window_accent_bright"
	tmux set -g @theme468-pane-active-border-foreground-suspended "$window_accent_dark"
	tmux set -g @theme468-pane-active-border-background "default"

	unset -f nord_colors
} && nord_colors
