function nord_colors {
	nord0="#2e3440"
	nord1="#3b4252"
	nord2="#434c5e"
	nord3="#4c566a"
	nord4="#d8dee9"
	nord5="#e5e9f0"
	nord6="#eceff4"
	nord7="#8fbcbb"
	nord8="#88c0d0"
	nord9="#81a1c1"
	nord10="#5e81ac"
	nord11="#bf616a"
	nord12="#d08770"
	nord13="#ebcb8b"
	nord14="#a3be8c"
	nord15="#b48ead"

	tmux set -g @theme468-status-foreground "$nord4"
	tmux set -g @theme468-status-background "$nord1"
	tmux set -g @theme468-mode-foreground "$nord0"
	tmux set -g @theme468-mode-background "$nord10"

	tmux set -g @theme468-window-foreground "$nord8"
	tmux set -g @theme468-window-background "$nord3"
	tmux set -g @theme468-window-current-foreground "$nord4"
	tmux set -g @theme468-window-current-background "$nord10"
	tmux set -g @theme468-window-current-background-suspended "$nord3"

	tmux set -g @theme468-segment-session-foreground "$nord0"
	tmux set -g @theme468-segment-session-foreground-prefix "$nord0"
	tmux set -g @theme468-segment-session-background "$nord8"
	tmux set -g @theme468-segment-session-background-suspended "$nord3"
	tmux set -g @theme468-segment-session-background-prefix "$nord4"

	tmux set -g @theme468-segment-host-foreground "$nord0"
	tmux set -g @theme468-segment-host-foreground-prefix "$nord0"
	tmux set -g @theme468-segment-host-background "$nord8"
	tmux set -g @theme468-segment-host-background-suspended "$nord3"
	tmux set -g @theme468-segment-host-background-prefix "$nord4"

	tmux set -g @theme468-segment-date-foreground "$nord8"
	tmux set -g @theme468-segment-date-background "$nord3"

	tmux set -g @theme468-message-style-foreground "$nord8"
	tmux set -g @theme468-message-style-background "$nord0"
	tmux set -g @theme468-message-command-style-foreground "$nord10"
	tmux set -g @theme468-message-command-style-background "$nord0"
	tmux set -g @theme468-copy-mode-match-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-match-style-background "$nord10"
	tmux set -g @theme468-copy-mode-current-match-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-current-match-style-background "$nord8"
	tmux set -g @theme468-copy-mode-mark-style-foreground "$nord0"
	tmux set -g @theme468-copy-mode-mark-style-background "$nord8"

	tmux set -g @theme468-display-panes-color "$nord3"
	tmux set -g @theme468-display-panes-active-color "$nord10"
	tmux set -g @theme468-pane-border-foreground "$nord3"
	tmux set -g @theme468-pane-border-background "default"
	tmux set -g @theme468-pane-active-border-foreground "$nord10"
	tmux set -g @theme468-pane-active-border-foreground-suspended "$nord3"
	tmux set -g @theme468-pane-active-border-background "default"

	unset -f nord_colors
} && nord_colors
