function tokyonight_night_colors {
  # from folke/tokyonight.nvim
  tnn_bg="#1a1b26"
  tnn_bg_dark="#16161e"
  tnn_bg_highlight="#292e42"
  tnn_blue="#7aa2f7"
  tnn_blue0="#3d59a1"
  tnn_blue1="#2ac3de"
  tnn_blue2="#0db9d7"
  tnn_blue5="#89ddff"
  tnn_blue6="#b4f9f8"
  tnn_blue7="#394b70"
  tnn_comment="#565f89"
  tnn_cyan="#7dcfff"
  tnn_dark3="#545c7e"
  tnn_dark5="#737aa2"
  tnn_fg="#c0caf5"
  tnn_fg_dark="#a9b1d6"
  tnn_fg_gutter="#3b4261"
  tnn_green="#9ece6a"
  tnn_green1="#73daca"
  tnn_green2="#41a6b5"
  tnn_magenta="#bb9af7"
  tnn_magenta2="#ff007c"
  tnn_orange="#ff9e64"
  tnn_purple="#9d7cd8"
  tnn_red="#f7768e"
  tnn_red1="#db4b4b"
  tnn_teal="#1abc9c"
  tnn_terminal_black="#414868"
  tnn_yellow="#e0af68"
  tnn_git_add="#449dab"
  tnn_git_change="#6183bb"
  tnn_git_delete="#914c54"

  tmux set -g @theme468-status-foreground "$tnn_fg"
  tmux set -g @theme468-status-background "$tnn_bg_dark"
  tmux set -g @theme468-mode-foreground "$tnn_fg"
  tmux set -g @theme468-mode-background "$tnn_fg_gutter"

  tmux set -g @theme468-window-foreground "$tnn_blue5"
  tmux set -g @theme468-window-background "$tnn_bg_highlight"
  tmux set -g @theme468-window-current-foreground "$tnn_bg_highlight"
  tmux set -g @theme468-window-current-background "$tnn_blue5"
  tmux set -g @theme468-window-current-background-suspended "$tnn_bg_dark"

  tmux set -g @theme468-segment-session-foreground "$tnn_bg_dark"
  tmux set -g @theme468-segment-session-foreground-prefix "$tnn_bg_dark"
  tmux set -g @theme468-segment-session-background "$tnn_blue"
  tmux set -g @theme468-segment-session-foreground-suspended "$tnn_dark3"
  tmux set -g @theme468-segment-session-background-suspended "$tnn_bg_dark"
  tmux set -g @theme468-segment-session-background-prefix "$tnn_green"

  tmux set -g @theme468-segment-host-foreground "$tnn_bg_dark"
  tmux set -g @theme468-segment-host-foreground-prefix "$tnn_bg_dark"
  tmux set -g @theme468-segment-host-background "$tnn_blue"
  tmux set -g @theme468-segment-host-foreground-suspended "$tnn_dark3"
  tmux set -g @theme468-segment-host-background-suspended "$tnn_bg_dark"
  tmux set -g @theme468-segment-host-background-prefix "$tnn_green"

  tmux set -g @theme468-segment-date-foreground "$tnn_blue"
  tmux set -g @theme468-segment-date-background "$tnn_fg_gutter"

  tmux set -g @theme468-message-style-foreground "$tnn_blue"
  tmux set -g @theme468-message-style-background "$tnn_bg"
  tmux set -g @theme468-message-command-style-foreground "$tnn_blue5"
  tmux set -g @theme468-message-command-style-background "$tnn_bg"
  tmux set -g @theme468-copy-mode-match-style-foreground "$tnn_bg"
  tmux set -g @theme468-copy-mode-match-style-background "$tnn_blue5"
  tmux set -g @theme468-copy-mode-current-match-style-foreground "$tnn_base"
  tmux set -g @theme468-copy-mode-current-match-style-background "$tnn_blue"
  tmux set -g @theme468-copy-mode-mark-style-foreground "$tnn_bg"
  tmux set -g @theme468-copy-mode-mark-style-background "$tnn_blue"

  tmux set -g @theme468-display-panes-color "$tnn_dark3"
  tmux set -g @theme468-display-panes-active-color "$tnn_blue5"
  tmux set -g @theme468-pane-border-foreground "$tnn_dark3"
  tmux set -g @theme468-pane-border-foreground-suspended "$tnn_bg_dark"
  tmux set -g @theme468-pane-border-background "default"
  tmux set -g @theme468-pane-active-border-foreground "$tnn_blue5"
  tmux set -g @theme468-pane-active-border-foreground-suspended "$tnn_dark3"
  tmux set -g @theme468-pane-active-border-background "default"

  unset -f tokyonight_night_colors
} && tokyonight_night_colors
