# k9s theme is downloaded in private_dot_config/k9s/skins/.chezmoiexternal.yaml
# to avoid a symlink

alacritty:
  url: https://github.com/catppuccin/alacritty/archive/main.tar.gz
  type: archive
  refreshPeriod: "168h"
  stripComponents: 1
  include:
    - "alacritty-main/catppuccin*.toml"
